// <auto-generated />
using System;
using Bank.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bank_Web.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260226011111_AddZipBytesToZipFileUploadDetails")]
    partial class AddZipBytesToZipFileUploadDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bank.Web.Models.BankCustomerDetails", b =>
                {
                    b.Property<Guid>("BankCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CkycNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Eircode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPEP")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KycUploadId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PPSN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<short>("RiskRating")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceOfFunds")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BankCustomerId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountyId");

                    b.HasIndex("KycUploadId")
                        .IsUnique();

                    b.ToTable("BankCustomerDetails", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.BankEmployee", b =>
                {
                    b.Property<Guid>("BankEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.HasKey("BankEmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("BankEmployee", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("CityId");

                    b.HasIndex("CountyId", "CityName")
                        .IsUnique();

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.County", b =>
                {
                    b.Property<Guid>("CountyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("CountyId");

                    b.HasIndex("CountyName")
                        .IsUnique();

                    b.ToTable("County", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.CustomerImage", b =>
                {
                    b.Property<Guid>("CustomerImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankCustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("DocumentType")
                        .HasColumnType("smallint");

                    b.Property<string>("FileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ImageBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerImageId");

                    b.HasIndex("BankCustomerId");

                    b.HasIndex("FileHashSha256");

                    b.ToTable("CustomerImages", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.DownloadResponseDecrypted", b =>
                {
                    b.Property<Guid>("DownloadRespDecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CkycNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("DecryptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("DownloadStatus")
                        .HasColumnType("smallint");

                    b.Property<Guid>("KycUploadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RequestRef")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("DownloadRespDecId");

                    b.HasIndex("KycUploadId");

                    b.ToTable("DownloadResponseDecrypted", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.DownloadResponseEncrypted", b =>
                {
                    b.Property<Guid>("DownloadRespEncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CipherAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CiphertextBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IvBase64")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("KycUploadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestRef")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("DownloadRespEncId");

                    b.HasIndex("KycUploadId");

                    b.ToTable("DownloadResponseEncrypted", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.KycUpdationResponse", b =>
                {
                    b.Property<Guid>("KycUpdateRespId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CkycNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("KycUploadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestRef")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<short>("UpdateStatus")
                        .HasColumnType("smallint");

                    b.HasKey("KycUpdateRespId");

                    b.HasIndex("KycUploadId");

                    b.ToTable("KYCUpdationResponse", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.KycUploadDetails", b =>
                {
                    b.Property<Guid>("KycUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CkycNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<short>("DedupeStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Eircode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsPEP")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<short>("OcrStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("PPSN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RequestRef")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<short>("RiskRating")
                        .HasColumnType("smallint");

                    b.Property<short>("Source")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceOfFunds")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ValidationStatus")
                        .HasColumnType("smallint");

                    b.HasKey("KycUploadId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountyId");

                    b.HasIndex("IdentityHash");

                    b.HasIndex("RequestRef")
                        .IsUnique();

                    b.ToTable("KYCUpload_Details", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.KycUploadImage", b =>
                {
                    b.Property<Guid>("KycUploadImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("DocumentType")
                        .HasColumnType("smallint");

                    b.Property<string>("ExtractedDocNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly?>("ExtractedExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ImageBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("KycUploadId")
                        .HasColumnType("uuid");

                    b.Property<float>("OcrConfidence")
                        .HasColumnType("real");

                    b.Property<string>("OcrText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KycUploadImageId");

                    b.HasIndex("FileHashSha256");

                    b.HasIndex("KycUploadId");

                    b.ToTable("KYCUpload_Images", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.SearchResponseDecrypted", b =>
                {
                    b.Property<Guid>("SearchRespDecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecryptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KycUploadId")
                        .HasColumnType("uuid");

                    b.Property<float?>("MatchScore")
                        .HasColumnType("real");

                    b.Property<string>("MatchedCkycNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("RequestRef")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<short>("SearchStatus")
                        .HasColumnType("smallint");

                    b.HasKey("SearchRespDecId");

                    b.HasIndex("KycUploadId");

                    b.ToTable("SearchResponseDecrypted", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.SearchResponseEncrypted", b =>
                {
                    b.Property<Guid>("SearchRespEncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CipherAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CiphertextBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IvBase64")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("KycUploadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestRef")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("SearchRespEncId");

                    b.HasIndex("KycUploadId");

                    b.ToTable("SearchResponseEncrypted", (string)null);
                });

            modelBuilder.Entity("ZipFileUploadDetails", b =>
                {
                    b.Property<Guid>("ZipUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid>("KycUploadId")
                        .HasColumnType("uuid");

                    b.Property<string>("SftpRemotePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<short>("UploadStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ZipBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("ZipFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ZipHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ZipSizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("ZipUploadId");

                    b.HasIndex("KycUploadId")
                        .IsUnique();

                    b.ToTable("ZipFileUploadDetails", (string)null);
                });

            modelBuilder.Entity("Bank.Web.Models.BankCustomerDetails", b =>
                {
                    b.HasOne("Bank.Web.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bank.Web.Models.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bank.Web.Models.KycUploadDetails", "KycUpload")
                        .WithMany()
                        .HasForeignKey("KycUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("County");

                    b.Navigation("KycUpload");
                });

            modelBuilder.Entity("Bank.Web.Models.City", b =>
                {
                    b.HasOne("Bank.Web.Models.County", "County")
                        .WithMany("Cities")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("Bank.Web.Models.CustomerImage", b =>
                {
                    b.HasOne("Bank.Web.Models.BankCustomerDetails", "BankCustomer")
                        .WithMany("CustomerImages")
                        .HasForeignKey("BankCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankCustomer");
                });

            modelBuilder.Entity("Bank.Web.Models.DownloadResponseDecrypted", b =>
                {
                    b.HasOne("Bank.Web.Models.KycUploadDetails", "KycUpload")
                        .WithMany()
                        .HasForeignKey("KycUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KycUpload");
                });

            modelBuilder.Entity("Bank.Web.Models.DownloadResponseEncrypted", b =>
                {
                    b.HasOne("Bank.Web.Models.KycUploadDetails", "KycUpload")
                        .WithMany()
                        .HasForeignKey("KycUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KycUpload");
                });

            modelBuilder.Entity("Bank.Web.Models.KycUpdationResponse", b =>
                {
                    b.HasOne("Bank.Web.Models.KycUploadDetails", "KycUpload")
                        .WithMany()
                        .HasForeignKey("KycUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KycUpload");
                });

            modelBuilder.Entity("Bank.Web.Models.KycUploadDetails", b =>
                {
                    b.HasOne("Bank.Web.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bank.Web.Models.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("County");
                });

            modelBuilder.Entity("Bank.Web.Models.KycUploadImage", b =>
                {
                    b.HasOne("Bank.Web.Models.KycUploadDetails", "KycUpload")
                        .WithMany("Images")
                        .HasForeignKey("KycUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KycUpload");
                });

            modelBuilder.Entity("Bank.Web.Models.SearchResponseDecrypted", b =>
                {
                    b.HasOne("Bank.Web.Models.KycUploadDetails", "KycUpload")
                        .WithMany()
                        .HasForeignKey("KycUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KycUpload");
                });

            modelBuilder.Entity("Bank.Web.Models.SearchResponseEncrypted", b =>
                {
                    b.HasOne("Bank.Web.Models.KycUploadDetails", "KycUpload")
                        .WithMany()
                        .HasForeignKey("KycUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KycUpload");
                });

            modelBuilder.Entity("ZipFileUploadDetails", b =>
                {
                    b.HasOne("Bank.Web.Models.KycUploadDetails", "KycUpload")
                        .WithMany()
                        .HasForeignKey("KycUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KycUpload");
                });

            modelBuilder.Entity("Bank.Web.Models.BankCustomerDetails", b =>
                {
                    b.Navigation("CustomerImages");
                });

            modelBuilder.Entity("Bank.Web.Models.County", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Bank.Web.Models.KycUploadDetails", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
