// <auto-generated />
using System;
using CKYC.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CKYC.Server.Migrations
{
    [DbContext(typeof(CkycDbContext))]
    partial class CkycDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CKYC.Server.Models.AuditEvent", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("ActorType")
                        .HasColumnType("smallint");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint");

                    b.Property<string>("RequestRef")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("AuditEventId");

                    b.HasIndex("Action");

                    b.HasIndex("EntityType");

                    b.HasIndex("EventTimeUtc");

                    b.HasIndex("RequestRef");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("CKYC.Server.Models.CkycDocument", b =>
                {
                    b.Property<Guid>("CkycDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CkycProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("DocumentType")
                        .HasColumnType("smallint");

                    b.Property<string>("ExtractedDocNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly?>("ExtractedExpiryDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("FileBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<float?>("OcrConfidence")
                        .HasColumnType("real");

                    b.Property<string>("OcrText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CkycDocumentId");

                    b.HasIndex("CkycProfileId");

                    b.HasIndex("DocumentType");

                    b.HasIndex("FileHashSha256")
                        .IsUnique();

                    b.ToTable("CkycDocuments");
                });

            modelBuilder.Entity("CKYC.Server.Models.CkycProfile", b =>
                {
                    b.Property<Guid>("CkycProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CkycNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Eircode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsPEP")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PPSN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<short>("RiskRating")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceOfFunds")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CkycProfileId");

                    b.HasIndex("CkycNumber")
                        .IsUnique();

                    b.HasIndex("IdentityHash");

                    b.HasIndex("FirstName", "LastName", "DateOfBirth");

                    b.ToTable("CkycProfiles");
                });

            modelBuilder.Entity("CKYC.Server.Models.InboundFile", b =>
                {
                    b.Property<Guid>("InboundFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short>("FileRole")
                        .HasColumnType("smallint");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InboundSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedCkycDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("InboundFileId");

                    b.HasIndex("FileHashSha256");

                    b.HasIndex("InboundSubmissionId");

                    b.HasIndex("LinkedCkycDocumentId");

                    b.ToTable("InboundFiles");
                });

            modelBuilder.Entity("CKYC.Server.Models.InboundPackage", b =>
                {
                    b.Property<Guid>("InboundPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InboundSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ZipBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("InboundPackageId");

                    b.HasIndex("InboundSubmissionId");

                    b.ToTable("InboundPackages");
                });

            modelBuilder.Entity("CKYC.Server.Models.InboundSubmission", b =>
                {
                    b.Property<Guid>("InboundSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CkycNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("LinkedCkycProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestRef")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("InboundSubmissionId");

                    b.HasIndex("LinkedCkycProfileId");

                    b.HasIndex("RequestRef")
                        .IsUnique();

                    b.ToTable("InboundSubmissions");
                });

            modelBuilder.Entity("CKYC.Server.Models.CkycDocument", b =>
                {
                    b.HasOne("CKYC.Server.Models.CkycProfile", "Profile")
                        .WithMany("Documents")
                        .HasForeignKey("CkycProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CKYC.Server.Models.InboundFile", b =>
                {
                    b.HasOne("CKYC.Server.Models.InboundSubmission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("InboundSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CKYC.Server.Models.CkycDocument", "LinkedDocument")
                        .WithMany()
                        .HasForeignKey("LinkedCkycDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedDocument");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CKYC.Server.Models.InboundPackage", b =>
                {
                    b.HasOne("CKYC.Server.Models.InboundSubmission", "Submission")
                        .WithMany("Packages")
                        .HasForeignKey("InboundSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CKYC.Server.Models.InboundSubmission", b =>
                {
                    b.HasOne("CKYC.Server.Models.CkycProfile", "LinkedProfile")
                        .WithMany()
                        .HasForeignKey("LinkedCkycProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedProfile");
                });

            modelBuilder.Entity("CKYC.Server.Models.CkycProfile", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("CKYC.Server.Models.InboundSubmission", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
